[program:green-deahan-queue]
command=php /var/www/green-deahan-booking/artisan queue:work database --sleep=3 --tries=3
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/green-deahan-booking/storage/logs/queue-worker.log
stopwaitsecs=3600

[program:green-deahan-scheduler]
command=php /var/www/green-deahan-booking/artisan schedule:work
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/green-deahan-booking/storage/logs/scheduler.log
